# Generated by Django 3.2.2 on 2021-07-04 12:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import markdownfield.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tags', '0001_initial'),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientContentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, default='', max_length=1200, null=True)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.document')),
            ],
        ),
        migrations.CreateModel(
            name='ClientContentWritten',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, default='', max_length=1200, null=True)),
                ('answer', models.TextField(blank=True, default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=250)),
                ('slug', models.SlugField(blank=True, default='', null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('rating', models.IntegerField(choices=[(0, 'Low'), (1, 'Normal'), (2, 'High')], default=0)),
                ('url', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('backgroundImage', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('backgroundImageUpload', models.ImageField(blank=True, null=True, upload_to='projects')),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('repo', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('content', markdownfield.models.MarkdownField(blank=True, null=True, rendered_field='content_rendered')),
                ('content_rendered', markdownfield.models.RenderedMarkdownField(null=True)),
                ('core_deps', models.ManyToManyField(blank=True, to='tags.Tag')),
                ('documents', models.ManyToManyField(blank=True, to='documents.Document')),
            ],
        ),
        migrations.CreateModel(
            name='ClientSuppliedContent',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('content_documents', models.ManyToManyField(blank=True, to='projects.ClientContentDocument')),
                ('content_written', models.ManyToManyField(blank=True, to='projects.ClientContentWritten')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.project')),
            ],
        ),
    ]
