# Generated by Django 3.2.2 on 2021-05-10 21:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChipTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=250)),
                ('created_on', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('url', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('backgroundImage', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('description', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('repo', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('content', models.TextField(blank=True, default='', null=True)),
                ('core_deps', models.ManyToManyField(to='projects.ChipTag')),
            ],
        ),
    ]
