# Generated by Django 3.2.2 on 2021-06-02 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_alter_privatedocument_file'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='documents',
            field=models.ManyToManyField(blank=True, null=True, to='documents.Document'),
        ),
    ]
