# Generated by Django 3.2.2 on 2021-07-04 16:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientcontentdocument',
            options={'verbose_name_plural': 'Client Documents'},
        ),
        migrations.AlterModelOptions(
            name='clientcontentwritten',
            options={'verbose_name_plural': 'Written Content'},
        ),
        migrations.AlterModelOptions(
            name='clientsuppliedcontent',
            options={'verbose_name_plural': 'Client Supplied Info'},
        ),
        migrations.AlterField(
            model_name='clientsuppliedcontent',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
