# Generated by Django 3.2.2 on 2021-06-02 16:34

from django.db import migrations
import markdownfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='content_rendered',
            field=markdownfield.models.RenderedMarkdownField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='content',
            field=markdownfield.models.MarkdownField(blank=True, null=True, rendered_field='content_rendered'),
        ),
    ]
