# Generated by Django 3.2.2 on 2021-05-13 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='backgroundImageUpload',
            field=models.ImageField(blank=True, null=True, upload_to='projects'),
        ),
        migrations.AlterField(
            model_name='project',
            name='core_deps',
            field=models.ManyToManyField(blank=True, to='projects.ChipTag'),
        ),
    ]
