# Generated by Django 3.2.2 on 2021-06-02 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_alter_privatedocument_file'),
        ('projects', '0003_auto_20210602_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='documents',
            field=models.ManyToManyField(blank=True, to='documents.Document'),
        ),
    ]
