# Generated by Django 3.2.2 on 2021-05-13 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20210513_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='rating',
            field=models.IntegerField(default=1),
        ),
    ]
