# Generated by Django 3.2.2 on 2021-05-10 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, default='', null=True)),
                ('email', models.TextField(blank=True, default='', null=True)),
                ('phone', models.TextField(blank=True, default='', null=True)),
                ('company', models.TextField(blank=True, default='', null=True)),
                ('website', models.TextField(blank=True, default='', null=True)),
                ('questions', models.TextField(blank=True, default='', null=True)),
                ('services_website', models.BooleanField(default=False)),
                ('services_business_application', models.BooleanField(default=False)),
                ('services_maintenance', models.BooleanField(default=False)),
                ('services_other', models.BooleanField(default=False)),
            ],
        ),
    ]
