# Generated by Django 3.2.2 on 2021-05-28 15:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('created_on', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('email', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('phone', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('company', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('website', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('questions', models.TextField(blank=True, default='', null=True)),
                ('services_website', models.BooleanField(default=False, verbose_name='Website Services')),
                ('services_business_application', models.BooleanField(default=False, verbose_name='Application Services')),
                ('services_maintenance', models.BooleanField(default=False, verbose_name='Maintenance')),
                ('services_other', models.BooleanField(default=False, verbose_name='Other Services')),
            ],
        ),
    ]
