# Generated by Django 3.2.2 on 2021-07-04 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(default='', max_length=250)),
                ('name_first', models.CharField(default='', max_length=250)),
                ('name_last', models.CharField(default='', max_length=250)),
                ('email', models.EmailField(default='', max_length=254)),
                ('phone', models.CharField(default='', max_length=12)),
                ('company', models.CharField(default='', max_length=250)),
                ('billing_address', models.CharField(default='', max_length=250)),
                ('shipping_address', models.CharField(default='', max_length=250)),
                ('website', models.URLField(default='', max_length=250)),
                ('documents', models.ManyToManyField(to='documents.Document')),
                ('projects', models.ManyToManyField(to='projects.Project')),
            ],
        ),
    ]
