# Generated by Django 3.2.2 on 2021-05-28 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='name',
            new_name='billing_address',
        ),
        migrations.AddField(
            model_name='client',
            name='company',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='client',
            name='display_name',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='client',
            name='name_first',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='client',
            name='name_last',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='client',
            name='phone',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='client',
            name='shipping_address',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='client',
            name='website',
            field=models.URLField(default='', max_length=250),
        ),
    ]
