# Generated by Django 3.2.2 on 2021-05-28 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contract',
        ),
    ]
