# Generated by Django 3.2.2 on 2021-07-03 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_auto_20210528_1643'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientContentWritten',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(default='', max_length=1200)),
                ('answer', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='ClientSuppliedContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.client')),
                ('written_content', models.ManyToManyField(to='clients.ClientContentWritten')),
            ],
        ),
    ]
