# Generated by Django 3.2.2 on 2021-07-03 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_clientcontentwritten_clientsuppliedcontent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientsuppliedcontent',
            name='client',
        ),
        migrations.RemoveField(
            model_name='clientsuppliedcontent',
            name='written_content',
        ),
        migrations.DeleteModel(
            name='ClientContentWritten',
        ),
        migrations.DeleteModel(
            name='ClientSuppliedContent',
        ),
    ]
