# Generated by Django 3.2.2 on 2021-07-03 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_alter_privatedocument_file'),
        ('projects', '0006_project_is_published'),
        ('clients', '0004_auto_20210703_0332'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='documents',
            field=models.ManyToManyField(to='documents.Document'),
        ),
        migrations.AddField(
            model_name='client',
            name='projects',
            field=models.ManyToManyField(to='projects.Project'),
        ),
    ]
