# Generated by Django 3.2.2 on 2021-05-10 21:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=250)),
                ('created_on', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('background', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('content', models.TextField(blank=True, default='', null=True)),
                ('tags', models.ManyToManyField(related_name='blog_tags', to='projects.ChipTag')),
            ],
        ),
    ]
