# Generated by Django 3.2.2 on 2021-07-04 12:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogTag',
            fields=[
                ('tag_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tags.tag')),
                ('usage_count', models.PositiveIntegerField(default=0)),
            ],
            bases=('tags.tag',),
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(default='', max_length=250)),
                ('created_on', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('background', models.CharField(blank=True, default='', help_text='http://...', max_length=250, null=True)),
                ('content', models.TextField(blank=True, default='', null=True)),
                ('tags', models.ManyToManyField(blank=True, related_name='blog_tags', to='blog.BlogTag')),
            ],
        ),
    ]
