# Generated by Django 3.2.2 on 2021-06-02 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tags', '0004_delete_blogtag'),
        ('clients', '0002_auto_20210528_1643'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=250)),
                ('objective', models.TextField(default='')),
                ('timeline', models.PositiveIntegerField(default=0)),
                ('client', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
                ('work_type', models.ManyToManyField(to='tags.Tag')),
            ],
        ),
    ]
