# Generated by Django 3.2.2 on 2021-06-02 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0004_delete_blogtag'),
        ('proposals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposalTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='proposal',
            name='objective',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='timeline',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='title',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='work_type',
            field=models.ManyToManyField(blank=True, to='tags.Tag'),
        ),
    ]
