# Generated by Django 3.2.2 on 2021-06-02 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0002_auto_20210602_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='theme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proposals.proposaltheme'),
        ),
    ]
