# Generated by Django 3.2.2 on 2021-05-28 15:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=250)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='PrivateDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=250)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('file', models.FileField(upload_to='documents/.private/')),
                ('doc_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='documents.documenttype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=250)),
                ('file', models.FileField(upload_to='documents/')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('doc_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='documents.documenttype')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
