# Generated by Django 3.2.2 on 2021-05-28 15:49

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatedocument',
            name='file',
            field=django_cryptography.fields.encrypt(models.FileField(upload_to='documents/.private/')),
        ),
    ]
