# Generated by Django 3.2.2 on 2021-05-28 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_privatedocument_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='notes',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='privatedocument',
            name='notes',
            field=models.TextField(default=''),
        ),
    ]
