# Generated by Django 3.2.2 on 2021-05-28 16:49

from django.db import migrations, models
import django_cryptography.fields
import django_encrypted_filefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_auto_20210528_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatedocument',
            name='file',
            field=django_encrypted_filefield.fields.EncryptedFileField(upload_to='documents/.private/'),
        ),
        migrations.AlterField(
            model_name='privatedocument',
            name='notes',
            field=django_cryptography.fields.encrypt(models.TextField(blank=True, default='', null=True)),
        ),
    ]
