# Generated by Django 3.2.2 on 2021-05-28 19:09

from django.db import migrations
import django_encrypted_filefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_auto_20210528_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatedocument',
            name='file',
            field=django_encrypted_filefield.fields.EncryptedFileField(upload_to='documents/private/'),
        ),
    ]
