# Generated by Django 3.2.2 on 2021-05-29 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogtag',
            name='usage_count',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
